# Generated by Django 4.0.5 on 2022-07-01 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default='This is the blog of mine that posts usefull info about programming language pythone', max_length=150)),
                ('profile_image', models.ImageField(upload_to='photo/profile/%Y/%m/%d')),
                ('phone', models.CharField(blank=True, default='----------------', max_length=50)),
                ('mobile', models.CharField(blank=True, default='----------------', max_length=50)),
                ('adress', models.CharField(blank=True, default='Uzbekistan', max_length=100)),
                ('website_url', models.CharField(blank=True, default='#', max_length=255)),
                ('github_url', models.CharField(blank=True, default='#', max_length=255)),
                ('instagram_url', models.CharField(blank=True, default='#', max_length=255)),
                ('facebook_url', models.CharField(blank=True, default='#', max_length=255)),
                ('telegram_url', models.CharField(blank=True, default='#', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
