# Generated by Django 4.0.5 on 2022-07-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='photo/profile/%Y/%m/%d'),
        ),
    ]
